id: ICF3953B7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T14:37:24+00:00'
last_modified: '2022-06-08T11:16:17.730903+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10016
  title: གསུང་ཐོར་བུ། བརྩོན་འགྲུས་གྲགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6787':
      image_group_id: I1KG10025
      title: ''
      total_pages: 728
      order: 1
      base_file: 6787.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
