id: P009470
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10016
  title: གསུང་ཐོར་བུ། བརྩོན་འགྲུས་གྲགས་པ།
  author: ''
  volumes:
    d2a148d54a4e430a8e1ffbb01950e84e:
      image_group_id: I1KG10025
      title: ''
      volume_number: 1
      total_pages: 728
